import {
  EAddressTable,
  EApiProvider,
  EApplicationStatus,
  ECompatibilityJob,
  EContractType,
  EExperienceLevel,
  ERemotePolicy,
  type IApplication,
  type IApplicationHasSkill,
  type IJobboard,
  type ISkill,
} from "@/modules/application/types";

/* ── Date helper ── */


//TODO : POur publishedAt renvoyer un code enum yesterday, 
const daysAgo = (days: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

/* ── Skills pool ── */

const skill = (id: number, label: string, createdAt: string): ISkill => ({
  id,
  label,
  createdAt,
  updatedAt: null,
  createdBy: 1,
});

const SKILLS = {
  react: skill(1, "React", "2024-06-01T00:00:00.000Z"),
  typescript: skill(2, "TypeScript", "2024-06-02T00:00:00.000Z"),
  nodejs: skill(3, "Node.js", "2024-06-03T00:00:00.000Z"),
  python: skill(4, "Python", "2024-06-04T00:00:00.000Z"),
  docker: skill(5, "Docker", "2024-06-05T00:00:00.000Z"),
  aws: skill(6, "AWS", "2024-06-06T00:00:00.000Z"),
  postgresql: skill(7, "PostgreSQL", "2024-06-07T00:00:00.000Z"),
  graphql: skill(8, "GraphQL", "2024-06-08T00:00:00.000Z"),
  vue: skill(9, "Vue.js", "2024-06-09T00:00:00.000Z"),
  java: skill(10, "Java", "2024-06-10T00:00:00.000Z"),
  spring: skill(11, "Spring Boot", "2024-06-11T00:00:00.000Z"),
  swift: skill(12, "Swift", "2024-06-12T00:00:00.000Z"),
  angular: skill(13, "Angular", "2024-06-13T00:00:00.000Z"),
  go: skill(14, "Go", "2024-06-14T00:00:00.000Z"),
  nestjs: skill(15, "NestJS", "2024-06-15T00:00:00.000Z"),
  nextjs: skill(16, "Next.js", "2024-06-16T00:00:00.000Z"),
  django: skill(17, "Django", "2024-06-17T00:00:00.000Z"),
  kubernetes: skill(18, "Kubernetes", "2024-06-18T00:00:00.000Z"),
  spark: skill(19, "Spark", "2024-06-19T00:00:00.000Z"),
  reactNative: skill(20, "React Native", "2024-06-20T00:00:00.000Z"),
};

const appSkills = (appId: number, skills: ISkill[]): IApplicationHasSkill[] =>
  skills.map((s) => ({ applicationId: appId, skillId: s.id, skill: s }));

const jobboardLinkedin: IJobboard = {
  id: 1,
  label: "LinkedIn",
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: null,
  createdBy: 1,
};

const jobboardIndeed: IJobboard = {
  id: 2,
  label: "Indeed",
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: null,
  createdBy: 1,
};

const jobboardWelcome: IJobboard = {
  id: 3,
  label: "Welcome to the Jungle",
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: null,
  createdBy: 1,
};

const jobboardFranceTravail: IJobboard = {
  id: 4,
  label: "France Travail",
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: null,
  createdBy: 1,
};

const jobboardHelloWork: IJobboard = {
  id: 5,
  label: "HelloWork",
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: null,
  createdBy: 1,
};

export const APPLICATION_MOCK_DATA: IApplication[] = [
  {
    id: 1,
    apiOfferId: null,
    title: "Développeur Full Stack React / Node.js",
    company: "Accenture",
    url: "https://example.com/job/1",
    description: "Mission de développement full stack en React et Node.js",
    publishedAt: daysAgo(0),
    appliedAt: "2025-01-15T10:00:00.000Z",
    createdAt: "2025-01-15T10:00:00.000Z",
    updatedAt: null,
    isFavorite: true,
    isArchived: false,
    apiProvider: EApiProvider.APIFY,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.MID,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.PERFECT,
    currentStatus: EApplicationStatus.ACCEPTED,
    salaryMin: 45000,
    salaryMax: 55000,
    userId: 1,
    jobboardId: 1,
    jobboard: jobboardLinkedin,
    applicationContacts: [],
    applicationSkills: appSkills(1, [SKILLS.react, SKILLS.typescript, SKILLS.nodejs, SKILLS.docker]),
    address: {
      id: 1,
      city: "Paris",
      postalCode: "75008",
      street: "118 Avenue des Champs-Élysées",
      complement: null,
      streetNumber: null,
      createdAt: "2025-01-15T10:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 1,
    },
  },
  {
    id: 2,
    apiOfferId: "FR-12345",
    title: "Ingénieur Logiciel Senior TypeScript",
    company: "Capgemini",
    url: "https://example.com/job/2",
    description: null,
    publishedAt: daysAgo(0),
    appliedAt: "2025-01-22T14:00:00.000Z",
    createdAt: "2025-01-22T14:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: EApiProvider.FRANCE_TRAVAIL,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.SENIOR,
    remotePolicy: ERemotePolicy.FULL,
    compatibility: ECompatibilityJob.ATTAINABLE,
    currentStatus: EApplicationStatus.IN_PROCESS,
    salaryMin: 55000,
    salaryMax: 70000,
    userId: 1,
    jobboardId: 4,
    jobboard: jobboardFranceTravail,
    applicationContacts: [],
    applicationSkills: appSkills(2, [SKILLS.typescript, SKILLS.nodejs, SKILLS.aws]),
    address: null,
  },
  {
    id: 3,
    apiOfferId: null,
    title: "Développeur Frontend React",
    company: "Doctolib",
    url: "https://example.com/job/3",
    description: "Rejoignez l'équipe frontend de Doctolib",
    publishedAt: daysAgo(1),
    appliedAt: "2025-01-20T09:00:00.000Z",
    createdAt: "2025-01-20T09:00:00.000Z",
    updatedAt: null,
    isFavorite: true,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.MID,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.PERFECT,
    currentStatus: EApplicationStatus.APPLIED,
    salaryMin: 50000,
    salaryMax: 60000,
    userId: 1,
    jobboardId: 3,
    jobboard: jobboardWelcome,
    applicationContacts: [],
    applicationSkills: appSkills(3, [SKILLS.react, SKILLS.typescript, SKILLS.graphql]),
    address: {
      id: 3,
      city: "Levallois-Perret",
      postalCode: "92300",
      street: "54 Quai Charles Pasqua",
      complement: null,
      streetNumber: null,
      createdAt: "2025-01-20T09:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 3,
    },
  },
  {
    id: 4,
    apiOfferId: "ADZUNA-9876",
    title: "Lead Developer JavaScript",
    company: null,
    url: "https://example.com/job/4",
    description: "Lead tech dans une startup fintech",
    publishedAt: daysAgo(1),
    appliedAt: null,
    createdAt: "2025-02-03T11:00:00.000Z",
    updatedAt: null,
    isFavorite: true,
    isArchived: false,
    apiProvider: EApiProvider.ADZUNA,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.SENIOR,
    remotePolicy: ERemotePolicy.FULL,
    compatibility: ECompatibilityJob.ATTAINABLE,
    currentStatus: EApplicationStatus.NEED_TO_APPLY,
    salaryMin: 65000,
    salaryMax: 80000,
    userId: 1,
    jobboardId: 2,
    jobboard: jobboardIndeed,
    applicationContacts: [],
    applicationSkills: appSkills(4, [SKILLS.react, SKILLS.nodejs, SKILLS.docker, SKILLS.aws, SKILLS.postgresql]),
    address: {
      id: 4,
      city: "Lyon",
      postalCode: "69002",
      street: "15 Place Bellecour",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-03T11:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 4,
    },
  },
  {
    id: 5,
    apiOfferId: null,
    title: "Développeur React Native Mobile",
    company: "BlaBlaCar",
    url: "https://example.com/job/5",
    description: "Développement d'applications mobiles React Native",
    publishedAt: daysAgo(2),
    appliedAt: "2025-01-28T10:00:00.000Z",
    createdAt: "2025-01-28T10:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.MID,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.PERFECT,
    currentStatus: EApplicationStatus.REJECTED,
    salaryMin: 48000,
    salaryMax: 58000,
    userId: 1,
    jobboardId: 5,
    jobboard: jobboardHelloWork,
    applicationContacts: [],
    applicationSkills: appSkills(5, [SKILLS.reactNative, SKILLS.typescript, SKILLS.react]),
    address: null,
  },
  {
    id: 6,
    apiOfferId: null,
    title: "Développeur Backend Node.js",
    company: "Contentsquare",
    url: "https://example.com/job/6",
    description: null,
    publishedAt: daysAgo(3),
    appliedAt: null,
    createdAt: "2025-02-05T15:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.FREELANCE,
    experience: EExperienceLevel.SENIOR,
    remotePolicy: ERemotePolicy.FULL,
    compatibility: ECompatibilityJob.ATTAINABLE,
    currentStatus: EApplicationStatus.NEED_TO_APPLY,
    salaryMin: 600,
    salaryMax: 750,
    userId: 1,
    jobboardId: 1,
    jobboard: jobboardLinkedin,
    applicationContacts: [],
    applicationSkills: appSkills(6, [SKILLS.nodejs, SKILLS.docker, SKILLS.postgresql, SKILLS.aws]),
    address: {
      id: 6,
      city: "Marseille",
      postalCode: "13001",
      street: "1 La Canebière",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-05T15:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 6,
    },
  },
  {
    id: 7,
    apiOfferId: "FR-55678",
    title: "Architecte Solutions Cloud & DevOps",
    company: "Thales",
    url: "https://example.com/job/7",
    description: "Conception d'architectures cloud sur AWS/Azure",
    publishedAt: daysAgo(4),
    appliedAt: "2025-02-01T09:00:00.000Z",
    createdAt: "2025-02-01T09:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: EApiProvider.FRANCE_TRAVAIL,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.SENIOR,
    remotePolicy: ERemotePolicy.ONSITE,
    compatibility: ECompatibilityJob.WHY_NOT,
    currentStatus: EApplicationStatus.GHOSTED,
    salaryMin: 60000,
    salaryMax: 75000,
    userId: 1,
    jobboardId: 4,
    jobboard: jobboardFranceTravail,
    applicationContacts: [],
    applicationSkills: appSkills(7, [SKILLS.aws, SKILLS.docker, SKILLS.kubernetes]),
    address: {
      id: 7,
      city: "Toulouse",
      postalCode: "31000",
      street: "5 Place du Capitole",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-01T09:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 7,
    },
  },
  {
    id: 8,
    apiOfferId: null,
    title: "Développeur Full Stack Python / React",
    company: "Datadog",
    url: "https://example.com/job/8",
    description: "Stack Python/Django côté backend, React côté frontend",
    publishedAt: daysAgo(5),
    appliedAt: "2025-02-10T11:00:00.000Z",
    createdAt: "2025-02-10T11:00:00.000Z",
    updatedAt: null,
    isFavorite: true,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.MID,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.PERFECT,
    currentStatus: EApplicationStatus.COMPANY_OFFER_RECEIVED,
    salaryMin: 55000,
    salaryMax: 65000,
    userId: 1,
    jobboardId: null,
    jobboard: null,
    applicationContacts: [],
    applicationSkills: appSkills(8, [SKILLS.python, SKILLS.react, SKILLS.django, SKILLS.postgresql]),
    address: null,
  },
  {
    id: 9,
    apiOfferId: "ADZUNA-1122",
    title: "Développeur JavaScript Junior",
    company: null,
    url: "https://example.com/job/9",
    description: "Développeur JS junior pour startup SaaS",
    publishedAt: daysAgo(6),
    appliedAt: "2025-02-14T10:00:00.000Z",
    createdAt: "2025-02-14T10:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: EApiProvider.ADZUNA,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.JUNIOR,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.WHY_NOT,
    currentStatus: EApplicationStatus.WITHDRAWN,
    salaryMin: 35000,
    salaryMax: 42000,
    userId: 1,
    jobboardId: 2,
    jobboard: jobboardIndeed,
    applicationContacts: [],
    applicationSkills: appSkills(9, [SKILLS.react, SKILLS.typescript]),
    address: {
      id: 9,
      city: "Nantes",
      postalCode: "44000",
      street: "2 Cours des 50 Otages",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-14T10:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 9,
    },
  },
  {
    id: 10,
    apiOfferId: null,
    title: "Tech Lead Frontend Vue.js",
    company: "Leboncoin",
    url: "https://example.com/job/10",
    description: "Lead technique pour une équipe de 5 développeurs frontend",
    publishedAt: daysAgo(8),
    appliedAt: null,
    createdAt: "2025-02-15T16:00:00.000Z",
    updatedAt: null,
    isFavorite: true,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.SENIOR,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.ATTAINABLE,
    currentStatus: EApplicationStatus.NEED_TO_APPLY,
    salaryMin: 65000,
    salaryMax: 80000,
    userId: 1,
    jobboardId: 5,
    jobboard: jobboardHelloWork,
    applicationContacts: [],
    applicationSkills: appSkills(10, [SKILLS.vue, SKILLS.typescript, SKILLS.nodejs, SKILLS.graphql]),
    address: null,
  },
  {
    id: 11,
    apiOfferId: "FR-77890",
    title: "Développeur Mobile iOS Swift",
    company: "SNCF Connect",
    url: "https://example.com/job/11",
    description: "Développement iOS en Swift/SwiftUI",
    publishedAt: daysAgo(10),
    appliedAt: "2025-02-12T14:00:00.000Z",
    createdAt: "2025-02-12T14:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: EApiProvider.FRANCE_TRAVAIL,
    contractType: EContractType.CDD,
    experience: EExperienceLevel.MID,
    remotePolicy: ERemotePolicy.ONSITE,
    compatibility: ECompatibilityJob.WHY_NOT,
    currentStatus: EApplicationStatus.APPLIED,
    salaryMin: 42000,
    salaryMax: 52000,
    userId: 1,
    jobboardId: 4,
    jobboard: jobboardFranceTravail,
    applicationContacts: [],
    applicationSkills: appSkills(11, [SKILLS.swift]),
    address: {
      id: 11,
      city: "Bordeaux",
      postalCode: "33000",
      street: "12 Place de la Bourse",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-12T14:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 11,
    },
  },
  {
    id: 12,
    apiOfferId: null,
    title: "Développeur React en Alternance",
    company: "Micropole",
    url: "https://example.com/job/12",
    description: "Alternance développeur React — rythme 3 semaines entreprise / 1 semaine école",
    publishedAt: daysAgo(14),
    appliedAt: "2025-02-03T10:00:00.000Z",
    createdAt: "2025-02-03T10:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.ALTERNANCE,
    experience: EExperienceLevel.JUNIOR,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.PERFECT,
    currentStatus: EApplicationStatus.IN_PROCESS,
    salaryMin: null,
    salaryMax: null,
    userId: 1,
    jobboardId: 1,
    jobboard: jobboardLinkedin,
    applicationContacts: [],
    applicationSkills: appSkills(12, [SKILLS.react, SKILLS.typescript]),
    address: {
      id: 12,
      city: "Paris",
      postalCode: "75009",
      street: "8 Rue de Mogador",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-03T10:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 12,
    },
  },
  {
    id: 13,
    apiOfferId: "ADZUNA-3344",
    title: "Consultant DevOps CI/CD",
    company: "Sopra Steria",
    url: "https://example.com/job/13",
    description: null,
    publishedAt: daysAgo(18),
    appliedAt: "2025-01-30T11:00:00.000Z",
    createdAt: "2025-01-30T11:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: EApiProvider.ADZUNA,
    contractType: EContractType.FREELANCE,
    experience: EExperienceLevel.SENIOR,
    remotePolicy: ERemotePolicy.FULL,
    compatibility: ECompatibilityJob.ATTAINABLE,
    currentStatus: EApplicationStatus.NEED_TO_APPLY,
    salaryMin: 550,
    salaryMax: 700,
    userId: 1,
    jobboardId: 2,
    jobboard: jobboardIndeed,
    applicationContacts: [],
    applicationSkills: appSkills(13, [SKILLS.docker, SKILLS.aws, SKILLS.kubernetes]),
    address: null,
  },
  {
    id: 14,
    apiOfferId: null,
    title: "Data Engineer Python / Spark",
    company: "OVHcloud",
    url: "https://example.com/job/14",
    description: "Conception et maintenance de pipelines de données",
    publishedAt: daysAgo(21),
    appliedAt: null,
    createdAt: "2025-02-16T17:00:00.000Z",
    updatedAt: null,
    isFavorite: true,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.MID,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.WHY_NOT,
    currentStatus: EApplicationStatus.NEED_TO_APPLY,
    salaryMin: 48000,
    salaryMax: 60000,
    userId: 1,
    jobboardId: 3,
    jobboard: jobboardWelcome,
    applicationContacts: [],
    applicationSkills: appSkills(14, [SKILLS.python, SKILLS.spark, SKILLS.postgresql, SKILLS.docker]),
    address: {
      id: 14,
      city: "Lille",
      postalCode: "59000",
      street: "Place du Général de Gaulle",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-16T17:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 14,
    },
  },
  {
    id: 15,
    apiOfferId: "FR-44556",
    title: "Développeur Backend Java / Spring Boot",
    company: "Crédit Agricole",
    url: "https://example.com/job/15",
    description: "Développement de services back-end en Java Spring Boot",
    publishedAt: daysAgo(35),
    appliedAt: "2025-01-16T10:00:00.000Z",
    createdAt: "2025-01-16T10:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: EApiProvider.FRANCE_TRAVAIL,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.MID,
    remotePolicy: ERemotePolicy.ONSITE,
    compatibility: ECompatibilityJob.ATTAINABLE,
    currentStatus: EApplicationStatus.REJECTED,
    salaryMin: 40000,
    salaryMax: 50000,
    userId: 1,
    jobboardId: 4,
    jobboard: jobboardFranceTravail,
    applicationContacts: [],
    applicationSkills: appSkills(15, [SKILLS.java, SKILLS.spring, SKILLS.postgresql]),
    address: null,
  },
  {
    id: 16,
    apiOfferId: null,
    title: "Développeur CDD Frontend Angular",
    company: null,
    url: "https://example.com/job/16",
    description: "CDD 6 mois dans une agence web — Angular 17+",
    publishedAt: daysAgo(45),
    appliedAt: "2025-02-06T09:00:00.000Z",
    createdAt: "2025-02-06T09:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.CDD,
    experience: EExperienceLevel.JUNIOR,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.PERFECT,
    currentStatus: EApplicationStatus.GHOSTED,
    salaryMin: 32000,
    salaryMax: 38000,
    userId: 1,
    jobboardId: 1,
    jobboard: jobboardLinkedin,
    applicationContacts: [],
    applicationSkills: appSkills(16, [SKILLS.angular, SKILLS.typescript]),
    address: {
      id: 16,
      city: "Montrouge",
      postalCode: "92120",
      street: "10 Avenue de la République",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-06T09:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 16,
    },
  },
  {
    id: 17,
    apiOfferId: "ADZUNA-5566",
    title: "Ingénieur Fullstack Go / React",
    company: "Qonto",
    url: "https://example.com/job/17",
    description: "Backend en Go, frontend en React — produit fintech B2B",
    publishedAt: daysAgo(55),
    appliedAt: null,
    createdAt: "2025-02-13T13:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: EApiProvider.ADZUNA,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.SENIOR,
    remotePolicy: ERemotePolicy.FULL,
    compatibility: ECompatibilityJob.PERFECT,
    currentStatus: EApplicationStatus.NEED_TO_APPLY,
    salaryMin: 65000,
    salaryMax: 85000,
    userId: 1,
    jobboardId: null,
    jobboard: null,
    applicationContacts: [],
    applicationSkills: appSkills(17, [SKILLS.go, SKILLS.react, SKILLS.postgresql, SKILLS.docker]),
    address: null,
  },
  {
    id: 18,
    apiOfferId: null,
    title: "Développeur Frontend React (Freelance)",
    company: "Startup IA confidentielle",
    url: "https://example.com/job/18",
    description: "Mission freelance 6 mois renouvelable — startup IA Paris",
    publishedAt: daysAgo(60),
    appliedAt: "2025-02-13T10:00:00.000Z",
    createdAt: "2025-02-13T10:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.FREELANCE,
    experience: EExperienceLevel.MID,
    remotePolicy: ERemotePolicy.FULL,
    compatibility: ECompatibilityJob.PERFECT,
    currentStatus: EApplicationStatus.APPLIED,
    salaryMin: 500,
    salaryMax: 650,
    userId: 1,
    jobboardId: 3,
    jobboard: jobboardWelcome,
    applicationContacts: [],
    applicationSkills: appSkills(18, [SKILLS.react, SKILLS.typescript, SKILLS.graphql, SKILLS.nextjs]),
    address: {
      id: 18,
      city: "Paris",
      postalCode: "75011",
      street: "42 Rue Oberkampf",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-13T10:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 18,
    },
  },
  {
    id: 19,
    apiOfferId: "FR-66778",
    title: "Développeur Alternant Backend Node.js",
    company: "Deezer",
    url: "https://example.com/job/19",
    description: "Alternance développeur backend — stack Node.js / PostgreSQL",
    publishedAt: daysAgo(90),
    appliedAt: "2025-01-07T10:00:00.000Z",
    createdAt: "2025-01-07T10:00:00.000Z",
    updatedAt: null,
    isFavorite: false,
    isArchived: false,
    apiProvider: EApiProvider.FRANCE_TRAVAIL,
    contractType: EContractType.ALTERNANCE,
    experience: EExperienceLevel.JUNIOR,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.ATTAINABLE,
    currentStatus: EApplicationStatus.WITHDRAWN,
    salaryMin: null,
    salaryMax: null,
    userId: 1,
    jobboardId: 4,
    jobboard: jobboardFranceTravail,
    applicationContacts: [],
    applicationSkills: appSkills(19, [SKILLS.nodejs, SKILLS.typescript, SKILLS.postgresql]),
    address: null,
  },
  {
    id: 20,
    apiOfferId: null,
    title: "Développeur Full Stack NestJS / Next.js",
    company: "ManoMano",
    url: "https://example.com/job/20",
    description: "Développement de features e-commerce — stack NestJS / Next.js",
    publishedAt: daysAgo(120),
    appliedAt: null,
    createdAt: "2025-02-17T09:00:00.000Z",
    updatedAt: null,
    isFavorite: true,
    isArchived: false,
    apiProvider: null,
    contractType: EContractType.CDI,
    experience: EExperienceLevel.MID,
    remotePolicy: ERemotePolicy.HYBRID,
    compatibility: ECompatibilityJob.PERFECT,
    currentStatus: EApplicationStatus.NEED_TO_APPLY,
    salaryMin: 50000,
    salaryMax: 62000,
    userId: 1,
    jobboardId: null,
    jobboard: null,
    applicationContacts: [],
    applicationSkills: appSkills(20, [SKILLS.nestjs, SKILLS.nextjs, SKILLS.typescript, SKILLS.react]),
    address: {
      id: 20,
      city: "Nantes",
      postalCode: "44200",
      street: "7 Rue de Strasbourg",
      complement: null,
      streetNumber: null,
      createdAt: "2025-02-17T09:00:00.000Z",
      updatedAt: null,
      tableName: EAddressTable.APPLICATION,
      tableId: 20,
    },
  },
];
